// module: the plain-language strategy summary card. Purpose: render the summary the OPERATOR'S AGENT wrote
// externally (research_notes kind='summary', served on the strategy detail contract) with an honest staleness
// badge. Invariants: ADVISORY ONLY — never the gate; the engine never generates this text; honest "No summary
// yet" empty state when null (never a fabricated narrative); markdown rendered as preserved-linebreak text
// (the codebase has no md renderer — same treatment as Agent notes).

import { BookOpenText } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Tooltip } from "@/components/ui/tooltip";
import { EmptyState } from "@/components/ui/honest-state";

export function SummaryCard({
  summaryMd,
  stale,
  updatedAt
}: {
  summaryMd?: string | null;
  stale?: boolean | null;
  updatedAt?: string | null;
}) {
  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-1.5">
          <BookOpenText className="size-4 text-iris-soft" /> Summary
          <Tooltip content="Written by the operator's agent from this Version's recorded facts only — what it trades, the hypothesis, what the deterministic Gate decided and why, and the forward-test state. Advisory, not the gate: the Gate alone funds or kills." />
        </CardTitle>
        <div className="flex flex-wrap items-center justify-end gap-1.5">
          <Badge variant="muted">written by the operator&apos;s agent · advisory, not the gate</Badge>
          {stale ? <Badge variant="warn">stale — numbers changed since this was written</Badge> : null}
        </div>
      </CardHeader>
      <CardContent>
        {summaryMd ? (
          <div className="space-y-2">
            <div className="whitespace-pre-wrap text-[13px] leading-relaxed text-muted">{summaryMd}</div>
            {updatedAt ? (
              <div className="text-[11px] text-quiet">
                written <time dateTime={updatedAt}>{new Date(updatedAt).toLocaleString("en-US")}</time>
              </div>
            ) : null}
          </div>
        ) : (
          <EmptyState
            title="No summary yet."
            hint="The operator's agent writes a plain-language summary from this Version's recorded facts. It appears here once written — nothing is auto-generated by the engine."
          />
        )}
      </CardContent>
    </Card>
  );
}
