// module: SummaryCard — the plain-language strategy summary rendered as an Iris Bento `.card` (used where
// the standalone detail page wants the summary inside a bordered cell rather than the inline `.ai-sec`
// panel). Purpose: render the summary the OPERATOR'S AGENT wrote externally (research_notes kind='summary',
// served on the strategy detail contract) with an honest staleness badge. ADVISORY ONLY — never the gate;
// the engine never generates this text; honest "No summary yet" empty state when null (never a fabricated
// narrative); markdown rendered as preserved-linebreak text (the codebase has no md renderer).

export function SummaryCard({
  summaryMd,
  stale,
  updatedAt
}: {
  summaryMd?: string | null;
  stale?: boolean | null;
  updatedAt?: string | null;
}) {
  return (
    <div className="card">
      <div className="card-hdr">
        <span
          className="card-lbl"
          data-tip="Written by the operator's agent from this Version's recorded facts only — advisory, not the gate. The Gate alone funds or kills."
        >
          Summary
        </span>
        <div className="chip-row">
          <span className="badge badge-run">operator&apos;s agent · advisory</span>
          {stale ? <span className="badge" style={{ color: "var(--gold)", borderColor: "oklch(0.82 0.14 85 / 0.32)" }}>stale</span> : null}
        </div>
      </div>
      <div className="card-body">
        {summaryMd ? (
          <>
            <div className="ai-body" style={{ whiteSpace: "pre-wrap" }}>{summaryMd}</div>
            {updatedAt ? (
              <div className="quiet" style={{ fontSize: 9.5, marginTop: 6 }}>
                written <time dateTime={updatedAt}>{new Date(updatedAt).toLocaleString("en-US")}</time>
              </div>
            ) : null}
          </>
        ) : (
          <p className="ai-body quiet">
            No summary yet — the operator&apos;s agent writes a plain-language summary from this Version&apos;s recorded
            facts. It appears here once written; nothing is auto-generated by the engine.
          </p>
        )}
      </div>
    </div>
  );
}
