-- 013: Rename prompts/prompt_versions to research_prompts/research_prompt_versions
-- This makes naming consistent with trader_prompts / trader_prompt_versions.

-- Rename core tables
alter table if exists prompts rename to research_prompts;
alter table if exists prompt_versions rename to research_prompt_versions;

-- Rename sequences (if auto-generated by PK defaults)
-- PostgreSQL auto-renames sequences tied to columns, but the prompt_number
-- sequence was manually created, so rename it explicitly:
do $$
begin
  if exists (select 1 from pg_class where relname = 'prompts_prompt_number_seq') then
    alter sequence prompts_prompt_number_seq rename to research_prompts_prompt_number_seq;
  end if;
end $$;

-- Rename constraints for clarity (cosmetic, keeps pg_dump readable)
alter table research_prompts rename constraint prompts_pkey to research_prompts_pkey;
alter table research_prompt_versions rename constraint prompt_versions_pkey to research_prompt_versions_pkey;

-- The FK from research_prompt_versions → research_prompts
alter table research_prompt_versions rename constraint prompt_versions_prompt_id_fkey to research_prompt_versions_prompt_id_fkey;

-- The unique constraint on (prompt_id, version)
do $$
begin
  if exists (select 1 from pg_constraint where conname = 'prompt_versions_prompt_id_version_key') then
    alter table research_prompt_versions rename constraint prompt_versions_prompt_id_version_key to research_prompt_versions_prompt_id_version_key;
  end if;
end $$;

-- Rename indexes (cosmetic)
do $$
begin
  if exists (select 1 from pg_class where relname = 'prompts_prompt_number_idx') then
    alter index prompts_prompt_number_idx rename to research_prompts_prompt_number_idx;
  end if;
end $$;
